environment:
  matrix:
    - COMPILER: g++
      ARCH: "i686"

    - COMPILER: g++
      ARCH: "x86_64"

cache:
  - mingw-w32-bin-i686-20161221.7z
  - mingw-w64-bin-x86_64-20161221.7z

skip_commits:
# Add [av skip] to commit messages for docfixes, etc to reduce load on queue
  message: /\[av skip\]/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

build_script:
  - C:\MinGW\msys\1.0\bin\sh --login /c/projects/world-cmake/msys_build.sh

artifacts:
  - path: '**\*.dll'
    name: WORLD
